In [1]:
import sys
from pathlib import Path

ROOT_DIR = Path().resolve().parents[2]
sys.path.insert(0, str(ROOT_DIR))

In [2]:

import os
import pandas as pd
from langchain_groq.chat_models import ChatGroq
from dotenv import load_dotenv
from src.RAG.Constants.models import GroqModelList

gml = GroqModelList()

load_dotenv('../../Secrets/RAG.env')
GROQ_API_KEY = os.getenv('GROQ_API_KEY','')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY','')
print(len(GROQ_API_KEY))

/home/who/Documents/Coding/Freelance_Projects/Freelance_P-01_Cuisine-Menu-Recommendation-App/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

56

In [3]:
llm_groq = ChatGroq(
    model=gml.openai.gpt_oss_20b,
    temperature=0.7,
    api_key=GROQ_API_KEY,    
)
llm_groq.invoke(input='What LLM model are you?')

AIMessage(content='I’m built on OpenAI’s GPT‑4 architecture.', additional_kwargs={'reasoning_content': 'User asks: "What LLM model are you?" We need to answer. According to policy, we should say we are based on GPT-4 architecture. We should not mention policy. Provide answer.'}, response_metadata={'token_usage': {'completion_tokens': 63, 'prompt_tokens': 78, 'total_tokens': 141, 'completion_time': 0.06406473, 'completion_tokens_details': {'reasoning_tokens': 42}, 'prompt_time': 0.004245873, 'prompt_tokens_details': None, 'queue_time': 0.048553197, 'total_time': 0.068310603}, 'model_name': 'openai/gpt-oss-20b', 'system_fingerprint': 'fp_e99e93f2ac', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019c0821-cb92-74c2-84e0-32b1926f783d-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 78, 'output_tokens': 63, 'total_tokens': 141, 'output_token_details': {'reasoning': 42}})

In [4]:
graph_schema = """
node_label {node_property: dtype}:
Country {ids: str, name: str, iso_code: str, coords: list[float], boundingbox: list[float]}
State {ids: str, name: str, iso_code: str, coords: list[float], boundingbox: list[float]}
City {ids: str, name: str, coords: list[float], boundingbox: list[float]}
Area {ids: str, name: str}
Locality {ids: str, name: str}
Restaurant {ids: int, name: str, city: str, area: str, locality: str, cuisines: List[str], rating: float | null, address: str, coords: List[float] | null, chain: bool, city_id: str}
Menu {name: str, category: str, description: str, types: Literal["VEG", "NONVEG", "EGG", "UNKNOWN"], cuisine: str}
MainCuisine {name: str}

link_label {link_property: dtype}:
HAS_STATE {}
HAS_CITY {}
HAS_AREA {}
HAS_LOCALITY {}
HAS_RESTAURANT {}
HAS_MENU {price: int | null, rating: float | null}
SERVES_MAIN_CUISINE {}

Relationships:
(:Country)-[:HAS_STATE]->(:State)
(:State)-[:HAS_CITY]->(:City)
(:City)-[:HAS_AREA]->(:Area)
(:Area)-[:HAS_LOCALITY]->(:Locality)
(:Locality)-[:HAS_RESTAURANT]->(:Restaurant)
(:Restaurant)-[:HAS_MENU]->(:Menu)
(:Restaurant)-[:SERVES_MAIN_CUISINE]->(:MainCuisine)
"""

In [5]:
cypher_pattern = """
Allowed query patterns:

# Search for Restaurants based on location change to city.ids
PATTERN 1.1: Search for Restaurants by City
MATCH (:City {name:$city})-[]-()-[]-()-[:HAS_RESTAURANT]->(r:Restaurant)
RETURN r LIMIT 5000 DESC r.ids

PATTERN 1.2: Search for Restaurants by Area
MATCH (:Area {name:$area})-[]-()-[:HAS_RESTAURANT]->(r:Restaurant)
RETURN r LIMIT 5000 DESC r.ids

PATTERN 1.3: Search for Restaurants by Locality
MATCH (:Locality {name:$locality})-[:HAS_RESTAURANT]->(r:Restaurant)
RETURN r LIMIT 5000 DESC r.ids

# Search for Menus based on location
PATTERN 2.1: Search for Menus by City
MATCH (:City {name:$city})-[]-()-[]-()-[:HAS_RESTAURANT]->()-[:HAS_MENU]-(m:Menu)
RETURN m LIMIT 5000 DESC m.name

PATTERN 2.2: Search for Menus by Area
MATCH (:Area {name:$area})-[]-()-[:HAS_RESTAURANT]->()-[:HAS_MENU]-(m:Menu)
RETURN m

PATTERN 2.3: Search for Menus by Locality
MATCH (:Locality {name:$locality})-[:HAS_RESTAURANT]->()-[:HAS_MENU]-(m:Menu)
RETURN m

# Search for Menus based on cuisines



PATTERN_2: Restaurant by cuisine
MATCH (r:Restaurant)-[:SERVES]->(cu:Cuisine {name:$cuisine})
RETURN r

PATTERN_3: Restaurant by city AND cuisine
MATCH (r:Restaurant)-[:LOCATED_IN]->(c:City {name:$city}),
      (r)-[:SERVES]->(cu:Cuisine {name:$cuisine})
RETURN r

PATTERN_4: Similar restaurants
MATCH (r:Restaurant {name:$name})-[s:SIMILAR_TO]->(other)
RETURN other ORDER BY s.score DESC

Task:
- Select the SINGLE best pattern
- Output ONLY:
  pattern_name
  parameter_values

"""

In [6]:

system_prompt = f"""
You are a graph query planner.

You MUST follow these rules:
- Use ONLY the node labels listed below.
- Use ONLY the relationship types listed below.
- Use ONLY the properties listed below.
- Do NOT invent new labels, relationships, or properties.
- If a question cannot be answered using this schema, respond with:
  "NOT_ANSWERABLE_WITH_SCHEMA"

Graph schema:
{graph_schema}

You are NOT allowed to use any other schema elements.

"""

In [7]:
from src.ETL.Config.graph_pool import GraphPool

graph = GraphPool.get_graph(graph_name='test')
graph

In [8]:
# get best rated menus from best rated restaurants serving thai cuisines in Koramangala
from time import time


graph_query = """
MATCH (:Area {name: 'Koramangala'})-[*2]->(rstn:Restaurant)-[]->(:MainCuisine {name: 'Thai'})
WHERE rstn.rating > 4.0
MATCH (rstn)-[link:HAS_MENU]-(menu:Menu)
WHERE link.rating > 4.0
RETURN DISTINCT
    rstn.name,
    menu.name,
    menu.types,
    link.price,
    link.rating
ORDER BY link.rating DESC
LIMIT 2000
"""
st = time()
result = graph.query(graph_query).result_set
print(f"Time taken for graph query: {(time() - st)*1000:.2f} ms")
df = pd.DataFrame([row for row in result], columns=['Restautant','Name', 'Type', 'Price', 'Rating'])


df.head(10)

Time taken for graph query: 269.14 ms

,Restautant,Name,Type,Price,Rating
0,Bamey's Restro Cafe,Paneer Chilly,VEG,315.0,5.0
1,Momo Rice Noodles,Fish Manchurian Gravy,NONVEG,370.0,5.0
2,Momo Rice Noodles,Veg Chilli Garlic Curry with Rice,VEG,250.0,5.0
3,Momo Rice Noodles,Chilli Crispy Fish Dry,NONVEG,370.0,5.0
4,Momo Rice Noodles,Spicy Curd Chicken Lollipop ( 6 pic),NONVEG,331.0,5.0
5,Momo Rice Noodles,Veg Butter Garlic Noodles,VEG,225.0,5.0
6,Beijing Bites,Hunan Tofu,VEG,299.0,5.0
7,Momo Rice Noodles,Pork Schezwan Fried Rice,NONVEG,290.0,5.0
8,Momo Rice Noodles,Seafood Mushroom Clear Soup,NONVEG,195.0,5.0
9,Thai Basil,Stir Fried Chicken Red Curry Paste,NONVEG,480.0,5.0

In [79]:
from typing import Literal, Dict, Any, List, Set

In [80]:
def get_competitors_data(
    q_params: dict,
    output: Literal['dict', 'dataframe'] = 'dict',
    exclude: Set[str]={"ids", "city_id"},
) -> Dict[str, Any] | pd.DataFrame:
    graph_query = """
    MATCH (:Area {name: $area})-[:HAS_LOCALITY]->(:Locality)-[:HAS_RESTAURANT]->(r:Restaurant)
    MATCH (r)-[:SERVES_MAIN_CUISINE]->(:MainCuisine {name: $cuisine})
    WHERE r.rating IS NOT NULL AND r.rating >= $min_rating
    RETURN DISTINCT r
    ORDER BY r.rating DESC, r.name ASC
    LIMIT $limit
    """
    # include some menu pricing info. Min, Max, Mean, Median, Mode, SD.
    # All rstn in area's mean and sd, all rstn in area serving same cuisine
    # restructure the json to be {'column':[data]} instead of [{'col':data},{'col':data},]
    
    result = graph.query(graph_query, q_params).result_set
    nodes = [node[0] for node in result] # flatten data
    rqrd_data = {
        key: [
            ', '.join(str(item) for item in node.properties[key]) 
            if isinstance(node.properties[key], list) 
            else node.properties[key]
            for node in nodes
        ]
        for key in nodes[0].properties.keys() 
        if key not in exclude
    }
    # include query time in logs
    return pd.DataFrame(rqrd_data) if output=='dataframe' else rqrd_data

In [82]:
from src.RAG.Config.tool_models import GetCompetitorDataModels

f_params = GetCompetitorDataModels.FunctionParams(
    q_params=GetCompetitorDataModels.QueryParams(
        area='Indiranagar',
        cuisine='Thai',
        limit=200,
    ),
    output='dataframe',
    exclude={'ids','city_id',"locality", "city", "address", "coords"},
)
cmpt_data = get_competitors_data(**f_params.model_dump())
cmpt_data

,name,area,cuisines,rating,chain
0,Thai Basil,Indiranagar,Thai,4.6,True
1,SHARON TEA STALL,Indiranagar,"Thai, Bakery",4.5,True
2,Xian,Indiranagar,"Chinese, Thai",4.5,False
3,Beijing Bites,Indiranagar,"Chinese, Thai",4.4,True
4,Tiger Thai,Indiranagar,"Thai, Pan-Asian",4.4,False
5,Wok In Chow - Pure Vegetarian Asian Street Food,Indiranagar,"Chinese, Thai",4.4,False
6,China Garten,Indiranagar,"Chinese, Thai",4.3,False

In [183]:
def get_competitors_menu(
    q_params: dict,
    output: Literal['dict', 'dataframe'] = 'dict',
    exclude: Set[str]={"ids", "city_id"},
)-> Dict[str, Any] | pd.DataFrame:
    graph_query = """
    MATCH (:Area {name: $area})-[:HAS_LOCALITY]->(:Locality)-[:HAS_RESTAURANT]->(rstn:Restaurant)
    MATCH (rstn)-[:SERVES_MAIN_CUISINE]->(:MainCuisine {name: $cuisine})
    MATCH (rstn)-[link:HAS_MENU]->(menu:Menu)
    WHERE link.rating IS NOT NULL AND link.rating >= $min_menu_rating

    WITH rstn, menu, link
    ORDER BY rstn.name ASC, link.rating DESC, menu.name ASC

    WITH rstn, collect({
        rstn: properties(rstn),
        menu: properties(menu),
        food: properties(link)
    })[0..20] AS top_menus

    UNWIND top_menus AS merged
    RETURN merged
    LIMIT $limit
    """
    result = graph.query(graph_query, q_params).result_set
    full_data = {
        f"{key1}_{key2}".replace("menu_", "food_", 1): [
            (', '.join(str(item) for item in x) if isinstance(x, list) else x)
            if (x:= items[0][key1].get(key2, ''))
            else False
            for items in result
        ]
        for key1 in result[0][0].keys()
        for key2 in result[0][0][key1].keys()
        if f"{key1}_{key2}" not in exclude
    }
    return pd.DataFrame(full_data) if output=='dataframe' else full_data

In [201]:
from src.RAG.Config.tool_models import GetCompetitorMenuModels

f_params = GetCompetitorMenuModels.FunctionParams(
    q_params=GetCompetitorMenuModels.QueryParams(
        area='Indiranagar',
        cuisine='Thai',
        min_menu_rating=4.0,
        limit=500,
    ),
    output='dataframe',
    exclude={'rstn_city_id','rstn_ids', "rstn_city", "rstn_locality", "rstn_address", "rstn_coords"}
)
data = get_competitors_menu(**f_params.model_dump())
data

,rstn_name,rstn_area,rstn_cuisines,rstn_rating,rstn_chain,food_name,food_types,food_price,food_rating
0,China Garten,Indiranagar,"Chinese, Thai",4.3,False,Beijing Chilli Prawns,NONVEG,260,5.0
1,China Garten,Indiranagar,"Chinese, Thai",4.3,False,Hot Chilli Baby corn,VEG,150,5.0
2,China Garten,Indiranagar,"Chinese, Thai",4.3,False,Mixed Vegetable in Green Chilli Gravy,VEG,180,5.0
3,China Garten,Indiranagar,"Chinese, Thai",4.3,False,Prawns Chinese Chop suey,NONVEG,220,5.0
4,China Garten,Indiranagar,"Chinese, Thai",4.3,False,Spicy Vegetable Curry,VEG,170,5.0
...,...,...,...,...,...,...,...,...,...
111,Thai Basil,Indiranagar,Thai,4.6,True,Slice Grilled Beef Salad,NONVEG,540,5.0
112,Thai Basil,Indiranagar,Thai,4.6,True,Stir-Fried Squid With Curry Powder,NONVEG,595,5.0
113,Thai Basil,Indiranagar,Thai,4.6,True,Tomkha Prawns,NONVEG,590,5.0
114,Thai Basil,Indiranagar,Thai,4.6,True,Tomkha Seafood,NONVEG,495,5.0
115,Thai Basil,Indiranagar,Thai,4.6,True,Black Chilli Paste With Prawns,NONVEG,595,4.9

In [216]:
def get_menu_benchmark(
    q_params: dict,
    output: Literal['dict', 'dataframe'] = 'dict',
    exclude: Set[str] = {"ids", "city_id"},
)-> Dict[str, Any] | pd.DataFrame:
    graph_query = """
    MATCH (:Area {name: $area})-[:HAS_LOCALITY]->(:Locality)-[:HAS_RESTAURANT]->(r:Restaurant)
    MATCH (r)-[:SERVES_MAIN_CUISINE]->(:MainCuisine {name: $cuisine})
    MATCH (r)-[link:HAS_MENU]->(m:Menu)
    WHERE toLower(m.name) CONTAINS toLower($menu_name)
        AND link.price IS NOT NULL
    RETURN
        m.name,
        link.price,
        link.rating,
        r.name,
        r.rating
    ORDER BY link.price ASC
    LIMIT $limit
    """
    result = graph.query(graph_query, q_params).result_set
    full_data = result
    return pd.DataFrame(full_data) if output=='dataframe' else full_data

In [ ]:

f_params={
    'q_params':{
        "area": 'Indiranagar',
        "cuisine": 'Thai',
        "menu_name": 'Spicy Vegetable Curry',
        "limit": 200,
    },
    "output": 'dict',
    "exclude": {}
}

data = get_menu_benchmark(**f_params)
data

[['Spicy Vegetable Curry', 170, 5.0, 'China Garten', 4.3]]

In [277]:
def get_menu_oppourtunities(
    q_params: dict,
    output: Literal['dict', 'dataframe'] = 'dict',
    exclude: Set[str] = {"ids", "city_id"},
)-> Dict[str, Any] | pd.DataFrame:
    graph_query= """
    MATCH (:Area {name:$area})-[:HAS_LOCALITY]->(:Locality)-[:HAS_RESTAURANT]->(r:Restaurant)
    MATCH (r)-[:SERVES_MAIN_CUISINE]->(:MainCuisine {name:$cuisine})
    MATCH (r)-[link:HAS_MENU]->(m:Menu)
    WHERE link.rating IS NOT NULL AND link.rating >= $min_menu_rating
    WITH
        m.name AS menu_name,
        m.types AS types,
        count(DISTINCT r.ids) AS competitor_count,
        avg(link.rating) AS avg_menu_rating,
        min(link.price) AS min_menu_price,
        avg(link.price) AS avg_menu_price,
        max(link.price) AS max_menu_price,
        stDev(link.price) AS sd_menu_price
    RETURN
        menu_name, types,
        competitor_count,
        avg_menu_rating,
        min_menu_price,
        avg_menu_price,
        max_menu_price,
        sd_menu_price
    ORDER BY competitor_count ASC, avg_menu_rating DESC
    LIMIT $limit
    """
    result = graph.query(graph_query, q_params).result_set
    columns = ['food_name', 'food_types', 'no_of_competitors', 'avg_menu_rating', "min_menu_price", "avg_menu_price", "max_menu_price", "sd_menu_price"]
    full_data = {
        key: [
            item[columns.index(key)]
            for item in result
        ]
        for key in columns
    }
    return pd.DataFrame(full_data) if output=='dataframe' else full_data

In [285]:

f_params={
    'q_params':{
        "area": 'Koramangala',
        "cuisine": 'Thai',
        "min_menu_rating": 4.0,
        "limit": 1000,
    },
    "output": 'dataframe',
    "exclude": {}
}

data = get_menu_oppourtunities(**f_params)
data

,food_name,food_types,no_of_competitors,avg_menu_rating,min_menu_price,avg_menu_price,max_menu_price,sd_menu_price
0,Paneer Pepper Salt (dry),VEG,1,5.00,299.0,299.000000,299.0,0.000000
1,Chicken Hunan Steamed Rice,NONVEG,1,5.00,299.0,299.000000,299.0,0.000000
2,Fish In Pickle Chilli Sauce,NONVEG,1,5.00,499.0,499.000000,499.0,0.000000
3,Pork Mustard Momo (10 Pic),NONVEG,1,5.00,280.0,280.000000,280.0,0.000000
4,Rad Naa Tao Hoo,VEG,1,5.00,370.0,370.000000,370.0,0.000000
...,...,...,...,...,...,...,...,...
753,Chicken Thukpa,NONVEG,2,4.30,229.0,307.000000,385.0,110.308658
754,Veg Shanghai Fried Rice,VEG,2,4.30,225.0,237.000000,249.0,16.970563
755,Veg Hakka Noodles,VEG,2,4.30,219.0,224.500000,230.0,7.778175
756,Chicken Fried Rice,NONVEG,2,4.25,240.0,244.500000,249.0,6.363961
757,Veg Manchow Soup,VEG,3,4.50,165.0,196.666667,240.0,38.837267

In [286]:
def get_overpriced_menu(
    q_params: dict,
    output: Literal['dict', 'dataframe'] = 'dict',
    exclude: Set[str] = {"ids", "city_id"},
)-> Dict[str, Any] | pd.DataFrame:
    graph_query= """
    MATCH (:Area {name:$area})-[:HAS_LOCALITY]->(:Locality)-[:HAS_RESTAURANT]->(r:Restaurant)
    MATCH (r)-[:SERVES_MAIN_CUISINE]->(:MainCuisine {name:$cuisine})
    MATCH (r)-[link:HAS_MENU]->(m:Menu)
    WHERE link.price IS NOT NULL AND link.rating IS NOT NULL
    WITH
        m.name AS menu_name,
        avg(link.price) AS avg_price,
        avg(link.rating) AS avg_rating,
        count(*) AS listings
    WHERE listings >= $min_listings
    RETURN menu_name, avg_price, avg_rating, listings
    ORDER BY avg_price DESC, avg_rating ASC
    LIMIT $limit
    """
    result = graph.query(graph_query, q_params).result_set
    full_data = result
    # columns = ['food_name', 'food_types', 'no_of_competitors', 'avg_menu_rating', "min_menu_price", "avg_menu_price", "max_menu_price", "sd_menu_price"]
    # full_data = {
    #     key: [
    #         item[columns.index(key)]
    #         for item in result
    #     ]
    #     for key in columns
    # }
    return pd.DataFrame(full_data) if output=='dataframe' else full_data

In [295]:

f_params = {
    'q_params': {
        "area": 'Koramangala',
        "cuisine": 'Thai',
        "min_listings": 1,
        "limit": 1000,
    },
    "output": 'dict',
    "exclude": {}
}

data = get_overpriced_menu(**f_params)
data

[['Jasmine Rice with Basil Chicken And Fried Egg', 730.0, 5.0, 1],
 ['Deep Fried Fish Balls', 660.0, 4.0, 1],
 ['Stir Fried Seafood With Curry Powder', 660.0, 5.0, 1],
 ['Softshell Crab Chilli.', 635.0, 4.9, 1],
 ['Spicy Miso Ramen Pork.', 625.0, 4.4, 1],
 ['Pork Japanese Katsu Curry.', 625.0, 4.5, 1],
 ['Char Siu Pork Rice.', 625.0, 4.6, 1],
 ['Fritter Prawns', 605.0, 4.9, 1],
 ['Red Curry Seafood', 600.0, 3.0, 1],
 ['Tom Kha Seafood', 600.0, 4.0, 1],
 ['Pad Ke Maw Prawn (Spicy)', 600.0, 4.3, 1],
 ['Papaya Salad With Seafood', 600.0, 4.5, 1],
 ['Tom Yum Prawns', 600.0, 4.6, 1],
 ['Vermicelli Spicy Salad With Mint And Seafood', 600.0, 4.6, 1],
 ['Tom Yum Seafood', 600.0, 4.6, 1],
 ['Pad Thai Noodles With Seafood', 600.0, 4.6, 1],
 ['Seafood Spicy Salad With Mint', 600.0, 4.6, 1],
 ['Pad Thai Noodles With Prawns', 600.0, 4.7, 1],
 ['Tom Yum Noodles With Seafood', 600.0, 4.8, 1],
 ['Garlic Pepper Prawns', 600.0, 4.9, 1],
 ['Green Curry Prawns', 600.0, 5.0, 1],
 ['Red Curry Prawns', 600.0, 5.0, 1],
 ['Red Curry Squid', 600.0, 5.0, 1],
 ['Belgium Pork Spare Ribs.', 595.0, 4.9, 1],
 ['Deep Fried Prawn Balls', 595.0, 5.0, 1],
 ['Fried Rice Seafood', 585.0, 4.4, 1],
 ['Basil Fried Rice Prawns', 585.0, 4.8, 1],
 ['Fried Rice Prawns', 585.0, 4.8, 1],
 ['Basil Fried Rice Seafood', 585.0, 5.0, 1],
 ['Pork Manchurian Gravy', 580.0, 2.3, 1],
 ['Fried Rice Black Chilli Paste Prawns', 580.0, 3.0, 1],
 ['Spicy Curd Pork Dry', 580.0, 3.2, 1],
 ['Tom Yum Veg Soup', 580.0, 3.4, 1],
 ['Tom Yum Chicken Soup', 580.0, 4.6, 1],
 ['Roasted Chilli Pork Dry', 580.0, 4.6, 1],
 ['Roasted Chilli Pork Gravy', 580.0, 4.6, 1],
 ['Chilli Mustard Pork Dry', 580.0, 4.7, 1],
 ['Hot Pepper Pork Dry', 580.0, 4.7, 1],
 ['Cantonese Roasted Pork Dry', 580.0, 4.7, 1],
 ['Honey Spicy Pork Dry', 580.0, 4.8, 1],
 ['Singapore Roasted Pork Dry', 580.0, 4.9, 1],
 ['Pork Manchurian Dry', 580.0, 4.9, 1],
 ['Smoked Pork Dry', 580.0, 5.0, 1],
 ['Garlic Pepper Beef', 570.0, 4.0, 1],
 ['Nasi Goreng Non-Veg.', 545.0, 4.3, 1],
 ['Chicken Satay', 545.0, 4.4, 1],
 ['Pad Thai Noodles With Beef', 545.0, 4.4, 1],
 ['Hainanese Chicken Rice.', 545.0, 4.5, 1],
 ['Papaya Salad With Crispy Fish', 545.0, 4.5, 1],
 ['Rice Basil Beef And Fried Egg', 545.0, 4.7, 1],
 ['Tom Yum Noodles With Veg', 545.0, 4.7, 1],
 ['Rice Basil Chicken And Fried Egg', 545.0, 4.8, 1],
 ['Noodles With Braised Chicken', 545.0, 4.8, 1],
 ['Slice Grilled Beef Salad', 545.0, 5.0, 1],
 ['Cashew Nut Chicken', 545.0, 5.0, 1],
 ['Fried Rice Beef', 545.0, 5.0, 1],
 ['Beef Spicy Salad With Mint', 545.0, 5.0, 1],
 ['Clear Glass Noodles Soup Veg', 540.0, 3.1, 1],
 ['Veg Spring Roll(4 Pcs)', 540.0, 3.5, 1],
 ['Green Curry Veg', 540.0, 4.4, 1],
 ['Red Curry Veg', 540.0, 4.5, 1],
 ['Mixed Herb With Fried Chicken', 540.0, 4.7, 1],
 ['Red Curry Chicken', 540.0, 4.8, 1],
 ['Green Curry Chicken', 540.0, 4.8, 1],
 ['Fried Wonton With Chicken And Prawn', 540.0, 4.8, 1],
 ['Prawn Phad Phrik.', 535.0, 4.9, 1],
 ['Prawn Phad Thai.', 525.0, 3.6, 1],
 ['Nepali Thakali Set Fish', 525.0, 3.8, 1],
 ['Prawn Sen Yai Phad Kheemao.', 525.0, 3.8, 1],
 ['Nepali Thakali Set Mutton', 525.0, 4.4, 1],
 ['Chicken Japanese Katsu Curry.', 525.0, 4.6, 1],
 ['Prawns In Butter Garlic.', 525.0, 5.0, 1],
 ['Pad Ke Maw Veg (Spicy)', 520.0, 4.3, 1],
 ['Pad Ke Maw Chicken (Spicy)', 520.0, 4.3, 1],
 ['Fried Chicken Salted Wings', 520.0, 4.4, 1],
 ['Fried Rice Pineapple Veg', 520.0, 4.7, 1],
 ['Pad Thai Noodles With Veg', 515.0, 3.9, 1],
 ['Stir Fried Glass Noodles With Chicken', 515.0, 3.9, 1],
 ['Pad Thai Noodles With Chicken', 515.0, 4.6, 1],
 ['Papaya Salad With Papaya Salad With Fermented Fish Sauce', 510.0, 2.9, 1],
 ['Fried Wonton Veg', 510.0, 3.8, 1],
 ['Tom Kha Veg', 500.0, 4.0, 1],
 ['Lemon Spicy Chicken', 500.0, 4.4, 1],
 ['Tom Kha Chicken', 500.0, 4.9, 1],
 ['Fish In Pickle Chilli Sauce', 499.0, 5.0, 1],
 ['Fried Chicken Spicy Salad With Mint', 495.0, 3.0, 1],
 ['Noodles With Vegetables In Gravy', 495.0, 3.0, 1],
 ['Chicken Khaja Set', 495.0, 3.8, 1],
 ['Noodles With Chicken In Gravy', 495.0, 4.2, 1],
 ['Khauk-Shwe Prawn.', 495.0, 4.2, 1],
 ['Sliced Garlic Chicken.', 495.0, 4.3, 1],
 ['Gai Phad Phrik.', 495.0, 4.4, 1],
 ['Chicken Gaeng Kiew Wahn.', 495.0, 4.5, 1],
 ['Grilled Beef', 495.0, 4.7, 1],
 ['Tom Yum Talay', 495.0, 4.7, 1],
 ['Tofu Japanese Katsu Curry.', 495.0, 4.7, 1],
 ['Belgian Pork Bao.', 495.0, 4.7, 1],
 ['Deep Fried Mushroom Cake', 495.0, 4.9, 1],
 ['Tom Kha Talay', 495.0, 5.0, 1],
 ['Rad Naan - Talay', 494.0, 2.5, 1],
 ['Pad See Eww Talay', 494.0, 3.7, 1],
 ['Lab Talay', 494.0, 4.4, 1],
 ['Pad Thai Talay', 494.0, 4.8, 1],
 ['Yum Woon Sen Talay', 494.0, 5.0, 1],
 ['Guay Tiew Tom Yum Kung', 485.0, 4.5, 1],
 ['Mushroom Spicy Salad', 480.0, 3.8, 1],
 ['Mango Salad Veg For Vegetarian', 480.0, 4.0, 1],
 ['Basil Fried Rice Tofu', 480.0, 4.1, 1],
 ['Fried Rice Chicken', 480.0, 4.1, 1],
 ['Basil Fried Rice Chicken', 480.0, 4.2, 1],
 ['Fried Rice Tofu', 480.0, 4.3, 1],
 ['Stir Fried Tofu With Pepper And Salt', 480.0, 4.4, 1],
 ['Spicy Minced Chicken With Herbs', 480.0, 4.4, 1],
 ['Stir Fried Tofu Red Curry Paste', 480.0, 4.6, 1],
 ['Fried Rice Black Chilli Paste Chicken', 480.0, 4.6, 1],
 ['Garlic Pepper Chicken', 480.0, 4.6, 1],
 ['Thai Papaya Salad Veg For Vegetarian', 480.0, 4.8, 1],
 ['Stir Fried Chicken Oyster Sauce', 480.0, 4.8, 1],
 ['Thai Papaya Salad / Sauces Non Veg', 480.0, 4.9, 1],
 ['Stir Fried Vegetable Tofu', 480.0, 4.9, 1],
 ['Rice With Omelette', 480.0, 4.9, 1],
 ['Stir Fried Vegetables Chicken', 480.0, 4.9, 1],
 ['Stir Fried Chicken Red Curry Paste', 480.0, 5.0, 1],
 ['Garlic Pepper Tofu', 480.0, 5.0, 1],
 ['Mango Salad Non-Veg', 480.0, 5.0, 1],
 ['Pramukh Ka Thiem', 476.0, 2.6, 1],
 ['Kung Pad Prikh Pao', 476.0, 4.2, 1],
 ['Pramukh Tod', 476.0, 4.7, 1],
 ['Kung Tod.', 476.0, 4.9, 1],
 ['Pad Woon Sen Ka Pao Kung', 476.0, 5.0, 1],
 ['Khauk-Shwe Chicken.', 475.0, 3.5, 1],
 ['Slice Chicken In Butter Garlic.', 475.0, 4.1, 1],
 ['Chicken Phad Thai.', 475.0, 4.4, 1],
 ['Chicken Sen Yai Phad Kheemao.', 475.0, 4.6, 1],
 ['Momo Platter Chicken Large 16 Pcs', 475.0, 4.6, 1],
 ['Veg Khaja Set', 475.0, 4.9, 1],
 ['Slice Chicken In Chilli Soya Garlic.', 475.0, 5.0, 1],
 ['Pla Sam Rot', 474.0, 4.5, 1],
 ['Rad Naa Kung', 470.0, 3.0, 1],
 ['Tom Yum Kung', 470.0, 4.4, 1],
 ['Keang Kheiywhhwan - Talay', 470.0, 5.0, 1],
 ['Tom Kha Kung', 470.0, 5.0, 1],
 ['Kung Satay', 460.0, 3.6, 1],
 ['Rice Basil Tofu', 460.0, 4.3, 1],
 ['Rice Basil Mushroom', 460.0, 4.4, 1],
 ['Khaow Pad Ka Phao Talay - Khai Dao', 460.0, 4.4, 1],
 ['Beijing Chicken', 459.0, 3.9, 1],
 ['Rad Naa Pramukh', 456.0, 5.0, 1],
 ['Nepali Thakali Set Chicken', 455.0, 2.7, 1],
 ['Prawn Kampung Rice.', 455.0, 4.6, 1],
 ['Prawn Mie Goreng.', 455.0, 4.7, 1],
 ['Chicken Nasi Goreng', 450.0, 3.1, 1],
 ['Spicy Miso Ramen Chicken.', 450.0, 4.4, 1],
 ['Korean Ramen Chicken.', 450.0, 4.5, 1],
 ['Khauk-Shwe Veg.', 450.0, 4.8, 1],
 ['Keang Kheiywhhwan -Kung', 445.0, 4.4, 1],
 ['Keang Phet Kung', 445.0, 4.5, 1],
 ['Kung Ka Thiem', 445.0, 4.6, 1],
 ['Prawn Sui Mai With Tobiko.', 445.0, 4.9, 1],
 ['Pad Ka Phao--Kung', 445.0, 5.0, 1],
 ['Shredded Chicken In Chilli Oil.', 445.0, 5.0, 1],
 ['Kung Pad Num Man Hoi', 445.0, 5.0, 1],
 ['Khaow Pad Ka Phao Kung - Khai Dao', 440.0, 3.0, 1],
 ['Pad Thai Kung', 435.0, 4.4, 1],
 ['Pad See Ew Kung', 435.0, 4.8, 1],
 ['Prawn Fritter Bao.', 435.0, 4.8, 1],
 ['Pad Woon Sen Sai Kung', 435.0, 5.0, 1],
 ['Smoked buff thali', 430.0, 3.6, 1],
 ['Khaow Pad Kung', 430.0, 3.7, 1],
 ['Kai Satay', 430.0, 3.8, 1],
 ['Dynamite Shrimps', 429.0, 4.8, 1],
 ['Veg Phad Thai.', 425.0, 4.4, 1],
 ['Momo Platter Veg Large 16 Pcs', 425.0, 4.6, 1],
 ['Korean Ramen Veg.', 425.0, 4.6, 1],
 ['Water Chestnut', 425.0, 4.6, 1],
 ['Chicken Kampung Rice.', 425.0, 4.7, 1],
 ['Chicken Thai Tom Yum Fried Rice.', 425.0, 4.7, 1],
 ['Chicken Cantonesse Coopsue', 425.0, 4.8, 1],
 ['Japanese Curry Ramen Eggplant.', 425.0, 4.9, 1],
 ['Chicken Mie Goreng.', 425.0, 4.9, 1],
 ['Assorted Vegetables In Chilli Basil.', 425.0, 5.0, 1],
 ['Glutinous Rice Balls In Coconut Milk', 425.0, 5.0, 1],
 ['Chicken Pineapple Fried Rice.', 425.0, 5.0, 1],
 ['Khaow Pad Ka Phao Neua - Khai Dao', 420.0, 3.2, 1],
 ['Hunan Sauce Chicken', 415.0, 3.9, 1],
 ['Oyster Sauce Chicken', 415.0, 5.0, 1],
 ['Neua Pad Prikh Pao', 415.0, 5.0, 1],
 ['Tom Kha Kai', 410.0, 4.8, 1],
 ['Tom Yum Kai', 410.0, 4.9, 1],
 ['Guay Tiew Tom Yum Neua', 405.0, 2.9, 1],
 ['Nepali Thakali Set Egg', 405.0, 3.5, 1],
 ['Guay Tiew Num Sai Neua', 405.0, 4.5, 1],
 ['Korean Chicken Bao.', 405.0, 4.7, 1],
 ['Rad Naa Kai', 405.0, 4.9, 1],
 ['Guay Tiew Tom Yum Kai', 405.0, 5.0, 1],
 ['Khaichiao Kung Sub', 400.0, 4.8, 1],
 ['Lab Neua', 400.0, 5.0, 1],
 ['Prawns In Hot Garlic Sauce', 399.0, 3.7, 1],
 ['Jhol Momos Buff', 399.0, 4.2, 1],
 ['Dragon Prawns', 399.0, 4.4, 1],
 ['Lemon Basil Prawns', 399.0, 4.6, 1],
 ['Golden Fried Prawns', 399.0, 4.6, 1],
 ['Burnt Pepper Prawns', 399.0, 4.8, 1],
 ['Thai Prawns Red Curry', 399.0, 4.8, 1],
 ['Kothey Momos Buff', 399.0, 4.9, 1],
 ['Sweet & Sour Prawns', 399.0, 5.0, 1],
 ['Prawns In Hot Bean Sauce', 399.0, 5.0, 1],
 ['Pad Ka Pao Nuea', 395.0, 2.6, 1],
 ['Buff Chilly', 395.0, 2.8, 1],
 ['Buff Sukuti Sandheko', 395.0, 3.5, 1],
 ['Tom Jud Kai', 395.0, 4.3, 1],
 ['Japanese Cheese Cake.', 395.0, 4.4, 1],
 ['Steamed Chicken & Prawn Wonton.', 395.0, 4.4, 1],
 ['Cheese Wontons.', 395.0, 4.6, 1],
 ['Millionaires Brownies.', 395.0, 4.8, 1],
 ['Yakitori Chicken & Leeks.', 395.0, 4.8, 1],
 ['Oriental chicken satay.', 395.0, 4.9, 1],
 ['Pad Woon Sen Ka Pao Neua', 395.0, 5.0, 1],
 ['Broccoli Bokchoy and Mushroom with Black pepper.', 395.0, 5.0, 1],
 ['Kai Pad Prikh Pao', 390.0, 2.5, 1],
 ['Pork Chilli Garlic Curry Fried Rice', 390.0, 3.0, 1],
 ['Kai Phad Phng Kari', 390.0, 3.1, 1],
 ['Pork Thai Red Curry Fried Rice', 390.0, 3.7, 1],
 ['Pad Woon Sen Sai Kai', 390.0, 4.0, 1],
 ['Pad Prikh Keang -Kai', 390.0, 4.3, 1],
 ['Keang Kheiywhhwan Tao Hoo', 390.0, 4.3, 1],
 ['Pad Woon Sen Ka Pao Kai', 390.0, 4.3, 1],
 ['Pad See Ew Kai', 390.0, 4.4, 1],
 ['Keang Phet Tao Hoo', 390.0, 4.4, 1],
 ['Pad Thai Kai', 390.0, 4.5, 1],
 ['Pork Steamed Curry Fried Rice', 390.0, 4.6, 1],
 ['Keang Kheiywhhwan -Kai', 390.0, 4.6, 1],
 ['Pad Ka Phao--Kai', 390.0, 4.7, 1],
 ['Kai Pad Khing', 390.0, 4.7, 1],
 ['Keang Phet Kai', 390.0, 4.7, 1],
 ['Kai Pad Num Man Hoi', 390.0, 4.7, 1],
 ['Pad Prieow Wan Tao Hoo', 390.0, 4.8, 1],
 ['Khaow Pad Ka Phao Kai - Khai Dao', 390.0, 4.8, 1],
 ['Pad Ka Pao Tao Hoo', 390.0, 4.9, 1],
 ['Kai Ka Thiem', 390.0, 4.9, 1],
 ['Yum Woonsen-Kai', 390.0, 5.0, 1],
 ['Momo Platter Chicken 12 Pcs', 385.0, 4.2, 1],
 ['Tofu & Water Chestnut Chilly Basil.', 385.0, 4.3, 1],
 ['Crispy Lotus Thai Chilly Basil.', 385.0, 4.4, 1],
 ['Vietnamese Summer Roll.', 385.0, 4.5, 1],
 ['Nepali Thakali Set Veg', 385.0, 4.5, 1],
 ['Sriracha Tofu Bao.', 385.0, 4.6, 1],
 ['Thai Chilli Mushroom Bao.', 385.0, 4.6, 1],
 ['Thai Chicken Green Curry', 385.0, 4.6, 1],
 ['Spicy Edamame Balado.', 385.0, 4.7, 1],
 ['Thai Chicken Red Curry', 385.0, 4.9, 1],
 ['Pad See Ew Tao Hoo', 380.0, 3.3, 1],
 ['Khai Yad Sai', 380.0, 4.3, 1],
 ['Pad Woon Sen Ka Pao Tao Hoo', 380.0, 4.6, 1],
 ['Khaow Pad Kai', 380.0, 4.9, 1],
 ['Burnt Pepper Fish', 379.0, 3.7, 1],
 ['Dragon Fish', 379.0, 4.0, 1],
 ['Lemon Basil Fish', 379.0, 4.4, 1],
 ['Fish Finger', 379.0, 4.6, 1],
 ['Fish In Chilli Garlic Sauce', 379.0, 4.8, 1],
 ['Hunan Fish', 379.0, 5.0, 1],
 ['Fish In Oyster Sauce', 379.0, 5.0, 1],
 ['Prawns In Sambal Sauce', 379.0, 5.0, 1],
 ['Lab Kai', 378.0, 5.0, 1],
 ['Fried Momos Buff', 375.0, 2.9, 1],
 ['Veg Pineapple Fried Rice.', 375.0, 4.4, 1],
 ['Chicken Potsticker.', 375.0, 4.6, 1],
 ['Steamed Edamame With Truffle.', 375.0, 4.6, 1],
 ['Veg Kampung Rice.', 375.0, 4.7, 1],
 ['Veg Mie Goreng.', 375.0, 4.7, 1],
 ['Veg Thai Tom Yum Fried Rice.', 375.0, 4.9, 1],
 ['Chilli Prawns Gravy', 370.0, 2.5, 1],
 ['Fish in Ginger Sauce', 370.0, 3.0, 1],
 ['Pad Thai Tao Hoo', 370.0, 3.9, 1],
 ['Prawns Schezwan Style Dry', 370.0, 4.0, 1],
 ['Thai Fried Fish', 370.0, 4.0, 1],
 ['Crispy Leefu Prawns Dry', 370.0, 4.0, 1],
 ['Fish Thai Red Curry', 370.0, 4.0, 1],
 ['Prawns in Thai Sauce', 370.0, 4.0, 1],
 ['Fish in Hot Garlic Gravy', 370.0, 4.0, 1],
 ['Fish Finger Dry', 370.0, 4.0, 1],
 ['Crispy Spinach Prawns Dry', 370.0, 4.0, 1],
 ['Chilli Prawns Dry', 370.0, 4.1, 1],
 ['Hot Pepper Prawns Dry', 370.0, 4.2, 1],
 ['Pepper Salt Fish Dry', 370.0, 4.4, 1],
 ['Fish Manchurian Dry', 370.0, 4.6, 1],
 ['Singapore Fish Dry', 370.0, 4.7, 1],
 ['Fish Chilli Dry', 370.0, 4.8, 1],
 ['Som Tum Pla - Ra', 370.0, 4.8, 1],
 ['Lemongrass Chilli Prawns Dry', 370.0, 4.9, 1],
 ['Rad Naa Tao Hoo', 370.0, 5.0, 1],
 ['Prawns Manchurian Dry', 370.0, 5.0, 1],
 ['Lemongrass Chilli Fish Dry', 370.0, 5.0, 1],
 ['Dragan Fish Dry', 370.0, 5.0, 1],
 ['Fish Manchurian Gravy', 370.0, 5.0, 1],
 ['Prawns in Hot Garlic Sauce', 370.0, 5.0, 1],
 ['Prawns in Hunan Sauce', 370.0, 5.0, 1],
 ['Prawns Manchurian Gravy', 370.0, 5.0, 1],
 ['Fish with Broccoli White Sauce', 370.0, 5.0, 1],
 ['Dragon Prawns Dry', 370.0, 5.0, 1],
 ['Chilli Crispy Fish Dry', 370.0, 5.0, 1],
 ['Thai Fried Prawns', 370.0, 5.0, 1],
 ['Fish in Hot Garlic Dry', 370.0, 5.0, 1],
 ['Fish Chilli Gravy', 370.0, 5.0, 1],
 ['Sandeko Momos Chicken', 365.0, 1.5, 1],
 ['Egg Thukpa', 365.0, 3.9, 1],
 ['Gravy Momos Chicken', 365.0, 4.2, 1],
 ['Chicken Wai Wai Pakayeko', 365.0, 4.7, 1],
 ['Tom Jud Tao Hoo Sai Woon Sen', 365.0, 4.8, 1],
 ['Tom Jud Hed - Woon Sen', 360.0, 2.0, 1],
 ['Thai Veg Red Curry With Steamed Rice', 360.0, 3.1, 1],
 ['Mixed Pad Thai', 360.0, 4.0, 1],
 ['Thai Veg Green Curry With Steamed Rice', 360.0, 4.8, 1],
 ['Tom Yum Tao Hoo', 360.0, 5.0, 1],
 ['Mixed Phad Ki Mao', 359.0, 4.2, 1],
 ['Mix Phad Ki Mao [Non-veg]', 359.0, 5.0, 1],
 ['Momo Platter Veg 12 Pcs', 355.0, 4.0, 1],
 ['Sen Mee Pad Ka Pao Tao Hoo', 350.0, 3.3, 1],
 ['Darjelling Momos Chicken', 350.0, 3.4, 1],
 ['Tao Hoo Ka Thiem', 350.0, 3.6, 1],
 ['Golbhedha & Timur Momos Chicken', 350.0, 3.7, 1],
 ['Pad Prikh Keang Tao Hoo', 350.0, 4.0, 1],
 ['Prawns Pad Thai', 350.0, 4.0, 1],
 ['Smoked pork with anishi', 350.0, 4.3, 1],
 ['Smoked buff with kholar', 350.0, 4.3, 1],
 ['Tandoori Momos Chicken', 350.0, 4.4, 1],
 ['Pad Pukh Tao Hoo', 350.0, 4.5, 1],
 ['Bhoot Momos Chicken', 350.0, 4.7, 1],
 ['Momo Platter Buff 8 Pcs', 350.0, 4.8, 1],
 ['Afghani Tandoori Momos Chicken', 350.0, 4.8, 1],
 ['Tao Hoo Pad Men Mamuang Himmapan', 350.0, 5.0, 1],
 ['Tsinghai Chicken', 349.0, 2.4, 1],
 ['Honey Hunan Chicken', 349.0, 3.2, 1],
 ['Dim Sum Chilli Chicken', 349.0, 3.3, 1],
 ['Chicken In Pickle Chilli Sauce', 349.0, 3.3, 1],
 ['Sweet & Sour Chicken', 349.0, 3.4, 1],
 ['Chicken In Hot Bean Sauce', 349.0, 3.6, 1],
 ['Chicken In Hoisin Sauce', 349.0, 3.7, 1],
 ['Taipei Chicken', 349.0, 3.9, 1],
 ['Roast Chicken In Chilli Plum Sauce', 349.0, 3.9, 1],
 ['Korean Bbq Chicken Wings (6 Pc)', 349.0, 4.0, 1],
 ['Hong Kong Chicken', 349.0, 4.0, 1],
 ['Burnt Pepper Chicken', 349.0, 4.0, 1],
 ["General Tso's Chicken", 349.0, 4.1, 1],
 ['Crispy Peking Chicken', 349.0, 4.1, 1],
 ['Chicken In Black Pepper Sauce', 349.0, 4.2, 1],
 ['Honey Chilli Chicken', 349.0, 4.2, 1],
 ['Chicken Lollipop', 349.0, 4.3, 1],
 ['Drums Of Heaven (chicken)', 349.0, 4.3, 1],
 ['Crispy Chicken Honey Pepper', 349.0, 4.3, 1],
 ['Great Wall Chicken', 349.0, 4.4, 1],
 ['Thai Chilli Chicken', 349.0, 4.4, 1],
 ['Lemon Basil Chicken', 349.0, 4.5, 1],
 ['Pan Fried Chicken With Celery & Onion', 349.0, 4.6, 1],
 ['Chicken With Lemon Sauce', 349.0, 4.7, 1],
 ['Kung Pao Chicken', 349.0, 4.7, 1],
 ['Ginger Chicken', 349.0, 4.7, 1],
 ['Crispy Spinach Chicken', 349.0, 4.7, 1],
 ['Chicken Pepper Salt', 349.0, 4.9, 1],
 ['Roast Chicken With Vegetables', 349.0, 4.9, 1],
 ['Chilli Basil Chicken', 349.0, 4.9, 1],
 ['Kai Phad Namprik (chicken)', 349.0, 5.0, 1],
 ['Tsing Hoi Chicken', 349.0, 5.0, 1],
 ['Vegetables In Manchurian Sauce', 345.0, 3.3, 1],
 ['Chilly Paneer', 345.0, 3.4, 1],
 ['Crunchy Salmon Maki.', 345.0, 4.0, 1],
 ['Sake (Salmon).', 345.0, 4.4, 1],
 ['Classic California Roll.', 345.0, 4.6, 1],
 ['Itame Maki', 345.0, 4.8, 1],
 ['Momo Platter Chicken 8 Pcs', 345.0, 4.9, 1],
 ['Dragon Chicken', 343.0, 4.1, 3],
 ['Tom Kha Hed', 340.0, 3.2, 1],
 ['Keang Kheiywhhwan Pukh', 340.0, 3.7, 1],
 ['Tom Yum Hed', 340.0, 4.0, 1],
 ['Pad See Ew Pukh', 340.0, 4.2, 1],
 ['Steam Momos Buff', 340.0, 4.2, 1],
 ['Pad Thai Pukh', 340.0, 4.5, 1],
 ['Pad Woon Sen Sai Pukh', 340.0, 4.6, 1],
 ['Som Tum Thai', 340.0, 4.6, 1],
 ['Tom Kha Tao Hoo', 340.0, 4.6, 1],
 ['Pad Woon Sen Ka Pao Pukh', 340.0, 4.8, 1],
 ['Keang Phet Hed', 340.0, 4.9, 1],
 ['Thai Fried Chicken', 339.5, 3.9, 2],
 ['Bhoot Wings', 335.0, 3.6, 1],
 ['Miso Veg Gyoza.', 335.0, 4.8, 1],
 ['Veg Wai Wai Pakayeko', 335.0, 4.8, 1],
 ['Spicy Curd Chicken Lollipop ( 6 pic)', 331.0, 5.0, 1],
 ['Spicy Curd Chicken', 330.0, 3.0, 1],
 ['Crispy Leefu Chicken', 330.0, 3.0, 1],
 ['Singapore Chicken', 330.0, 3.0, 1],
 ['Chicken Hunan Sauce', 330.0, 3.0, 1],
 ['Chilli Chicken Dry', 330.0, 3.3, 1],
 ['Chicken Hot Garlic Sauce', 330.0, 3.4, 1],
 ['Chilli Chicken Gravy', 330.0, 3.6, 1],
 ['Crispy Spanish Chicken', 330.0, 3.6, 1],
 ['Chicken with Coriander Sauce', 330.0, 3.6, 1],
 ['Honey Spicy Chicken Lollipop (6 pic)', 330.0, 3.7, 1],
 ['Shredded Chicken Green & Red Pepper Dry', 330.0, 3.8, 1],
 ['Chicken Pad Thai', 330.0, 4.0, 1],
 ['Crispy Lemongrass Chicken', 330.0, 4.1, 1],
 ['Shredded Chicken with Garlic Sauce', 330.0, 4.1, 1],
 ['Shredded Chicken Green & Red Pepper Gravy', 330.0, 4.1, 1],
 ['Crispy Chicken Lollipop(6 pic)', 330.0, 4.2, 1],
 ['Chicken Phad Ki Mao', 330.0, 4.2, 1],
 ['Crispy Schezwan Chicken', 330.0, 4.2, 1],
 ['Chicken Lollipop ( 6 pic)', 330.0, 4.3, 1],
 ['Chilli Chicken with Basil Sauce', 330.0, 4.3, 1],
 ['Smoked Chicken Dry', 330.0, 4.4, 1],
 ['Tao Hoo Pad Med Mamung Himaphan', 330.0, 4.5, 1],
 ['Chicken Manchurian Dry', 330.0, 4.6, 1],
 ['Chicken Manchurian Gravy', 330.0, 4.6, 1],
 ['Chicken with Mushroom White Sauce', 330.0, 4.7, 1],
 ['Hed Pad Num Mun Hoi', 330.0, 4.7, 1],
 ['Crispy Honey Spicy Chicken', 330.0, 4.8, 1],
 ['Pad Ka Pao Hed', 330.0, 4.8, 1],
 ['Chicken in Garlic Sauce', 330.0, 4.9, 1],
 ['Chicken Chilli Garlic Sauce', 330.0, 4.9, 1],
 ['Sliced Chicken with Oyster Sauce', 330.0, 5.0, 1],
 ['Crispy Chicken Finger', 330.0, 5.0, 1],
 ['Chicken Schezwan Sauce', 330.0, 5.0, 1],
 ['Chilli Chicken Dim Sum', 330.0, 5.0, 1],
 ['Hot Pepper Chicken', 330.0, 5.0, 1],
 ['Mixed Triple Schezwan Steamed Rice', 329.0, 4.0, 1],
 ['Dragon Prawns With Vegetable Chow Mein Bowl', 329.0, 4.0, 1],
 ['Chicken Steamed Momos', 329.0, 4.4, 1],
 ['Shredded Threaded Chicken', 329.0, 4.5, 1],
 ['Mixed Hunan Steamed Rice - Koithio', 329.0, 4.5, 1],
 ['Dragon Rolls With Garlic Sauce (chicken)', 329.0, 4.6, 1],
 ['Chicken Fried Momos', 329.0, 5.0, 1],
 ['Chicken Dragon Chopsuey', 327.0, 3.65, 2],
 ['Sandeko Momos Veg', 325.0, 3.3, 1],
 ['Chilly Chicken Boneless', 325.0, 4.0, 1],
 ['Darjelling Momos Veg', 325.0, 4.1, 1],
 ['Steam Momos Chicken', 325.0, 4.1, 1],
 ['Kothey Momos Chicken', 325.0, 4.2, 1],
 ['Spicy Chicken Katsu.', 325.0, 4.3, 1],
 ['Gravy Momos Veg', 325.0, 4.4, 1],
 ['Jhol Momos Chicken', 325.0, 4.5, 1],
 ['Ebi Tempura.', 325.0, 4.5, 1],
 ['Tandoori Momos Veg', 325.0, 4.7, 1],
 ['Afghani Tandoori Momos Veg', 325.0, 4.8, 1],
 ['Fried Momos Chicken', 325.0, 4.8, 1],
 ['Pandan Pudding In Coconut Cream', 325.0, 4.8, 1],
 ['Bhoot Momos Veg', 325.0, 4.9, 1],
 ['Crunchy Tuna Maki.', 325.0, 5.0, 1],
 ['Chicken American Chopsuey', 322.0, 3.8, 2],
 ['Smoked buff with potato', 320.0, 4.7, 1],
 ['Pearl Thai Milk Tea', 320.0, 4.9, 1],
 ['Mixed Khao Phad Kapro', 319.0, 2.2, 1],
 ['Prawn Hunan Steamed Rice - Koithio', 319.0, 4.0, 1],
 ['Prawn Triple Schezwan Steamed Rice', 319.0, 4.3, 1],
 ['Mixed Steamed Rice - Koithio', 319.0, 5.0, 1],
 ['Momo Platter Veg 8 Pcs', 315.0, 3.7, 1],
 ['Chicken Sandheko', 315.0, 4.0, 1],
 ['Prawns Khao Phad Kapro', 315.0, 4.1, 1],
 ['Chilly Chicken', 315.0, 4.3, 1],
 ['Jhol Momos Veg', 315.0, 4.5, 1],

In [296]:
len(data)

930